# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from appconf import AppConf


class NensAuthAppConf(AppConf):
    # These need configuration:
    CLIENT_ID = ''  # Generated by AWS Cognito
    CLIENT_SECRET = ''  # Generated by AWS Cognito
    REDIRECT_URI = ''  # Can only be hardcoded (AWS Cognito checks it exactly)

    # These are N&S-global settings:
    ACCESS_TOKEN_URL = "https://nens.auth.eu-west-1.amazoncognito.com/oauth2/token"
    AUTHORIZE_URL = "https://nens.auth.eu-west-1.amazoncognito.com/oauth2/authorize"
    JWKS_URI = "https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_9AyLE4ffV/.well-known/jwks.json"

    SCOPE = "openid email profile"  # phone / user profile admin could be added

    STANDALONE = False

    class Meta:
        prefix = 'nens_auth'
