# Generated by Django 2.2.16 on 2020-10-13 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import nens_auth_client.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nens_auth_client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('roles', models.TextField(default='[]', help_text='The role objects to be created after an invite is accepted.', validators=[nens_auth_client.models.validate_invite_roles])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
