# Generated by Django 2.2.16 on 2020-11-13 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.crypto
import functools
import nens_auth_client.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nens_auth_client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.CharField(default=functools.partial(django.utils.crypto.get_random_string, *(32,), **{}), max_length=32, primary_key=True, serialize=False)),
                ('status', models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Rejected'), (3, 'Revoked'), (4, 'Failed')], default=0)),
                ('expires', models.DateTimeField()),
                ('permissions', models.TextField(default='{}', help_text='The permissions to be set after an invite is accepted, as a JSON object. The expected JSON fields depends on the setting NENS_AUTH_PERMISSION_BACKEND. See the project README.', validators=[nens_auth_client.models._validate_permissions])),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites_sent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
