# Generated by Django 2.2.16 on 2021-01-18 09:33

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("nens_auth_client", "0004_remoteuser_add_tokens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="email",
            field=models.EmailField(
                help_text="Only users with this email address may accept this invitation.",
                max_length=254,
            ),
        ),
    ]
